### ISSUE TITLE
启动不了  这个是啥问题

### ISSUE THREAD

**Issue by TokyoHot998** [mdddj/simple_shop_v2#1]
![image](https://user-images.githubusercontent.com/20854221/121165699-0714b280-c883-11eb-85ec-c8875337f6e7.png)

**Comment by mdddj** [comment]
你的图片挂了
![image](https://user-images.githubusercontent.com/29020213/121165945-3b886e80-c883-11eb-977f-e145002abcf0.png)

**Comment by mdddj** [comment]
加群667186542

**Comment by TokyoHot998** [comment]
已解决   key.properties没弄好的问题
